from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from sqlalchemy import func
from typing import List, Dict, Any
from app.database.connection import get_db
from app.models.user import User, Admin
from app.models.scan import Scan
from app.models.prediction import Prediction
from app.models.report import Report
from app.utils.dependencies import get_current_admin

router = APIRouter(prefix="/admin", tags=["Admin Dashboard"])

@router.get("/analytics", response_model=Dict[str, Any])
def get_platform_analytics(
    db: Session = Depends(get_db),
    current_admin: Admin = Depends(get_current_admin)
):
    """Retrieve high-level platform statistics and data distributions."""
    total_users = db.query(User).count()
    total_scans = db.query(Scan).count()
    total_predictions = db.query(Prediction).count()
    total_reports = db.query(Report).count()
    
    # Cancer Type Breakdown
    cancer_breakdown = (
        db.query(Scan.cancer_type, func.count(Scan.id))
        .group_by(Scan.cancer_type)
        .all()
    )
    cancer_stats = {ct: count for ct, count in cancer_breakdown}
    
    # Risk Distribution
    risk_breakdown = (
        db.query(Prediction.prediction_label, func.count(Prediction.id))
        .group_by(Prediction.prediction_label)
        .all()
    )
    risk_stats = {rl: count for rl, count in risk_breakdown}
    
    # Recent users signup activity (last 5)
    recent_users = (
        db.query(User)
        .order_by(User.created_at.desc())
        .limit(5)
        .all()
    )
    
    recent_users_list = [
        {
            "id": u.id,
            "email": u.email,
            "full_name": u.full_name,
            "created_at": u.created_at
        }
        for u in recent_users
    ]
    
    return {
        "stats": {
            "total_users": total_users,
            "total_scans": total_scans,
            "total_predictions": total_predictions,
            "total_reports": total_reports
        },
        "cancer_distribution": cancer_stats,
        "risk_distribution": risk_stats,
        "recent_signups": recent_users_list
    }

@router.get("/users")
def list_users(
    db: Session = Depends(get_db),
    current_admin: Admin = Depends(get_current_admin)
):
    """List all registered users with their details and scan counts."""
    users = db.query(User).all()
    user_list = []
    
    for u in users:
        scan_count = db.query(Scan).filter(Scan.user_id == u.id).count()
        user_list.append({
            "id": u.id,
            "email": u.email,
            "full_name": u.full_name,
            "age": u.age,
            "gender": u.gender,
            "is_active": u.is_active,
            "is_admin": u.is_admin,
            "created_at": u.created_at,
            "scans_count": scan_count
        })
        
    return user_list

@router.get("/predictions")
def list_predictions(
    db: Session = Depends(get_db),
    current_admin: Admin = Depends(get_current_admin)
):
    """List all risk predictions generated by the system."""
    predictions = (
        db.query(Prediction)
        .order_by(Prediction.created_at.desc())
        .all()
    )
    
    pred_list = []
    for p in predictions:
        scan = p.scan
        user = scan.user if scan else None
        pred_list.append({
            "id": p.id,
            "scan_id": p.scan_id,
            "patient_name": user.full_name if user else "N/A",
            "patient_email": user.email if user else "N/A",
            "cancer_type": scan.cancer_type if scan else "N/A",
            "prediction": p.prediction_label,
            "confidence": p.confidence,
            "recommendation": p.recommendation,
            "created_at": p.created_at
        })
        
    return pred_list

@router.get("/reports")
def list_reports(
    db: Session = Depends(get_db),
    current_admin: Admin = Depends(get_current_admin)
):
    """List all clinical reports generated by the system."""
    reports = db.query(Report).order_by(Report.created_at.desc()).all()
    report_list = []
    
    for r in reports:
        pred = r.prediction
        scan = pred.scan if pred else None
        user = scan.user if scan else None
        
        report_list.append({
            "id": r.id,
            "prediction_id": r.prediction_id,
            "pdf_path": r.pdf_path,
            "patient_name": user.full_name if user else "N/A",
            "cancer_type": scan.cancer_type if scan else "N/A",
            "prediction": pred.prediction_label if pred else "N/A",
            "created_at": r.created_at
        })
        
    return report_list
